version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group all patch and minor production dependency updates together
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # Group all patch and minor development dependency updates together
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Keep major updates separate as they might contain breaking changes
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"